version: '3.8'
services:
  namesrv2:
    image: apache/rocketmq:5.3.2
    container_name: namesrv2
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
  broker-b-master:
    image: apache/rocketmq:5.3.2
    container_name: broker-b-master
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./conf/broker-b-master.conf:/home/rocketmq/rocketmq-5.3.2/conf/broker.conf
      - ./data/broker-b-master/store:/home/rocketmq/store
    networks:
      - rocketmq
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf
networks:
  rocketmq:
    driver: bridge
